spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: account_service
        uri: lb://account-service
        predicates:
        - Path=/account/customer/**
      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/customer/**
